title: 18F Public Hub
generated_page_title_format: '%s &mdash; 18F Public Hub'
public: true
destination: _site_public/hub
baseurl: /hub
assets:
  baseurl: /hub/assets

# For Google Analytics
google_analytics_ua: UA-48605964-1

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "bare"
      edit_info:
        repo: 18F/hub
        branch: master
  - scope:
      path: "private"
    values:
      published: false

jekyll_get:
  - data: team_raw
    json: 'https://team-api.18f.gov/public/api/team/'
    cache: false
  - data: locations_raw
    json: 'https://team-api.18f.gov/public/api/locations/'
    cache: false
  - data: projects_raw
    json: 'https://team-api.18f.gov/public/api/projects/'
    cache: false
  - data: departments_raw
    json: 'https://team-api.18f.gov/public/api/departments/'
    cache: false
  - data: working_groups_raw
    json: 'https://team-api.18f.gov/public/api/working-groups/'
    cache: false
  - data: guilds_raw
    json: 'https://team-api.18f.gov/public/api/guilds/'
    cache: false
  - data: skills_raw
    json: 'https://team-api.18f.gov/public/api/skills/'
    cache: false
  - data: interests_raw
    json: 'https://team-api.18f.gov/public/api/interests/'
    cache: false
