title: 18F Public Hub
generated_page_title_format: '%s &mdash; 18F Public Hub'
public: true
destination: _site_public/hub
baseurl: /hub
assets:
  baseurl: /hub/assets

# For Google Analytics
google_analytics_ua: UA-48605964-1

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "bare"
      edit_info:
        repo: 18F/hub
        branch: master
  - scope:
      path: "private"
    values:
      published: false
