
markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data

excerpt_separator: <!-- more -->
exclude:
- README.md
- LICENSE.md
- CONTRIBUTING.md
- deploy
- pages/README.md
- pages/private/README.md

permalink: pretty
tag_dir: tags
tag_title_prefix: "#"

sass:
  sass_dir: assets/_sass

# use where a full URL is appropriate (e.g. RSS, OG tags)
url: https://hub.18f.us

# metadata
title: 18F Hub
description: "18F Hub"

# private data
private_data_path: _data/private

# team member images
team_img_dir: assets/images/team
missing_team_member_img: logo-18f.jpg
guest_user_img: logo-18f.jpg

# Editable link idea from:
# https://github.com/blacktm/standard-jekyll-template/blob/gh-pages/_config.yml
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "bare"
      edit_info:
        repo: 18F/hub
        branch: master
  -
    scope:
      path: "pages/private"
    values:
      edit_info:
        repo: 18F/hub-pages-private
        prefix: pages/private/
