title: 18F Public Hub
generated_page_title_format: '%s &mdash; 18F Public Hub'
public: true
destination: _site_public/hub
baseurl: /hub
assets:
  baseurl: /hub/assets

editor_url: http://prose.io/#

# For Google Analytics
google_analytics_ua: UA-48605964-1
