markdown: redcarpet
redcarpet:
  extensions:
  - with_toc_data
highlighter: rouge

excerpt_separator: <!-- more -->
exclude:
- README.md
- LICENSE.md
- CONTRIBUTING.md
- deploy
- pages/private/README.md
- vendor
- go

permalink: pretty
tag_dir: tags
tag_title_prefix: "#"

sass:
  sass_dir: assets/_sass
  style: compressed

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - assets/js
    - assets/css

# use where a full URL is appropriate (e.g. RSS, OG tags)
url: https://hub.18f.us

# metadata
title: 18F Hub
description: "Team information, connections, and documentation"
generated_page_title_format: '%s &mdash; 18F Hub'

# private data
private_data_path: _data/private
private_pages_path: pages/private

# team member images
team_img_dir: assets/images/team
missing_team_member_img: logo-18f.jpg
guest_user_img: logo-18f.jpg

# Editable link idea from:
# https://github.com/blacktm/standard-jekyll-template/blob/gh-pages/_config.yml
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "bare"
      edit_info:
        repo: 18F/hub
        branch: master
  -
    scope:
      path: "pages/private"
    values:
      edit_info:
        repo: 18F/hub-pages-private
        prefix: pages/private/

editor_url: https://hub.18f.us/edit/#
midas_url: "https://midas.18f.us"

prose:
  rooturl: 'pages'
  media: 'assets'
  metadata:
    pages:
      - name: 'title'
        field:
          element: 'text'
      - name: 'permalink'
        field:
          element: 'text'

# Remove this when https://github.com/18F/hub/issues/209 is resolved.
full_rebuild: true

# For Google Analytics
google_analytics_ua: UA-48605964-24
