---
- name: Download Google Auth Proxy
  get_url:
    url=https://github.com/bitly/google_auth_proxy/releases/download/v1.0/google_auth_proxy-1.0.linux-amd64.go1.3.tar.gz
    dest=/home/vagrant/google_auth_proxy-1.0.linux-amd64.go1.3.tar.gz
- name: Unpack Google Auth Proxy
  unarchive:
    src=/home/vagrant/google_auth_proxy-1.0.linux-amd64.go1.3.tar.gz
    dest=/home/vagrant
    copy=no
- name: Symlink Google Auth Proxy
  file:
    src=/home/vagrant/google_auth_proxy-1.0.linux-amd64.go1.3/google_auth_proxy
    dest=/usr/local/18f/bin/google_auth_proxy
    state=link
- name: Copy Google Auth Proxy wrapper script
  copy:
    src=../../../../usr/local/18f/bin/google_auth_proxy.sh
    dest=/usr/local/18f/bin/google_auth_proxy.sh
- name: Copy Google Auth Proxy config
  copy:
    src=../../../../usr/local/18f/etc/google_auth_proxy.cfg
    dest=/usr/local/18f/etc/google_auth_proxy.cfg
- name: Copy Google Auth Proxy init script
  copy:
    src=../../../../etc/init.d/google_auth_proxy
    dest=/etc/init.d/google_auth_proxy
