#! /bin/sh

### BEGIN INIT INFO
# Provides:          google_auth_proxy
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the google_auth_proxy for the 18F Hub
# Description:       starts the google_auth_proxy for the 18F Hub
### END INIT INFO

###
# Originally sourced from Jamie Curle:
#   http://jamie.curle.io/blog/compiling-nginx-ubuntu/
#   https://s3-eu-west-1.amazonaws.com/jcurle/code/nginx.sh
# 
# Modified by Eric Mill, for 18F, 2014-07-15.
#   https://github.com/18f/DevOps
#
# Modified by Mike Bland, for 18F, 2014-11-24.
#   https://github.com/18F/hub
### 

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/18f/bin/google_auth_proxy.sh
DAEMON_OPTS="--config=/usr/local/18f/etc/google_auth_proxy.cfg"
NAME=google_auth_proxy
DESC=google_auth_proxy
LOGS=/var/log/google_auth_proxy
PIDFILE=/var/run/google_auth_proxy.run

test -x $DAEMON || exit 0

# Include nginx defaults if available
if [ -f /etc/default/google_auth_proxy ] ; then
        . /etc/default/google_auth_proxy
fi

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --pidfile $PIDFILE
        echo "$NAME."
        ;;
  restart|force-reload|reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --pidfile $PIDFILE
        sleep 1
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS
        echo "$NAME."
        ;;
# reload)
#         echo -n "Reloading $DESC configuration: "
#         start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE \
#             --exec $DAEMON
#         echo "$NAME."
#         ;;
      *)
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
            exit 1
            ;;
    esac

    exit 0
